// Generated by CoffeeScript 1.8.0
var h, w;

h = 700;

w = 1000;

d3.json("data.json", function(data) {
  var mychart;
  mychart = lodheatmap().height(h).width(w).zthresh(1.0);
  return d3.select("div#chart1").datum(data).call(mychart);
});

d3.json("data.json", function(data) {
  var lod_labels, mychart, times, x;
  times = (function() {
    var _results;
    _results = [];
    for (x in data.lodnames) {
      _results.push(x / 6);
    }
    return _results;
  })();
  lod_labels = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = times.length; _i < _len; _i++) {
      x = times[_i];
      _results.push(formatAxis(times, 1)(x));
    }
    return _results;
  })();
  mychart = lodheatmap().height(h).width(w).zthresh(1.0).quantScale(times).lod_labels(lod_labels);
  return d3.select("div#chart2").datum(data).call(mychart);
});
