// Generated by CoffeeScript 1.4.0
(function() {
  var draw;

  draw = function(data) {
    var Xaxis, Yaxis, click, clicked, curMarker, darkGray, h, hInner, i, jitter, jitterAmount, leftsvg, leftyScale, lightGray, m, markerdots, mouseout, mouseover, ngen, nmarkers, onedig, pad, pheMax, pheMin, pink, purple, rightdots, rightsvg, w, wInner, wL, wLInner, xScale, yScale;
    w = 500;
    h = 700;
    pad = {
      left: 60,
      top: 20,
      right: 40,
      bottom: 40
    };
    wInner = w - pad.left - pad.right;
    hInner = h - pad.top - pad.bottom;
    wL = 300;
    wLInner = wL - pad.left - pad.right;
    leftsvg = d3.select("body").append("svg").attr("id", "leftsvg").attr("width", wL).attr("height", h);
    rightsvg = d3.select("body").append("svg").attr("id", "rightsvg").attr("width", w).attr("height", h);
    lightGray = d3.rgb(230, 230, 230);
    darkGray = d3.rgb(200, 200, 200);
    pink = "#E9CFEC";
    purple = "#8C4374";
    leftsvg.append("rect").attr("x", pad.left).attr("y", pad.top).attr("height", hInner).attr("width", wLInner).attr("class", "innerBox").style("pointer-events", "none");
    rightsvg.append("rect").attr("x", pad.left).attr("y", pad.top).attr("height", hInner).attr("width", wInner).attr("class", "innerBox").style("pointer-events", "none");
    nmarkers = data.markers.length;
    pheMin = d3.min(data.pheno);
    pheMax = d3.max(data.pheno);
    ngen = data.genonames.length;
    leftyScale = d3.scale.ordinal().domain(d3.range(nmarkers)).rangePoints([pad.top, pad.top + hInner], 1);
    xScale = d3.scale.ordinal().domain(d3.range(ngen)).rangePoints([pad.left, pad.left + wInner], 1);
    yScale = d3.scale.linear().domain([pheMin, pheMax]).range([pad.top + hInner * 0.98, pad.top + hInner * 0.02]);
    Xaxis = rightsvg.append("g");
    Yaxis = rightsvg.append("g");
    Yaxis.selectAll("empty").data(yScale.ticks(10)).enter().append("line").attr("y1", function(d) {
      return yScale(d);
    }).attr("y2", function(d) {
      return yScale(d);
    }).attr("x1", pad.left).attr("x2", pad.left + wInner).attr("stroke", "white").attr("fill", "none").attr("stroke-width", "1").style("pointer-events", "none");
    onedig = d3.format(".1f");
    Yaxis.selectAll("empty").data(yScale.ticks(10)).enter().append("text").text(function(d) {
      return onedig(d);
    }).attr("y", function(d) {
      return yScale(d);
    }).attr("x", pad.left * 0.7);
    Yaxis.append("text").text("phenotype").attr("y", pad.top + hInner / 2).attr("x", pad.left * 0.3).attr("transform", "rotate(270," + (pad.left * 0.3) + "," + (pad.top + hInner / 2) + ")").attr("fill", "blue");
    Xaxis.selectAll("empty").data(data.genonames).enter().append("line").attr("x1", function(d, i) {
      return xScale(i);
    }).attr("x2", function(d, i) {
      return xScale(i);
    }).attr("y1", pad.top).attr("y2", pad.top + hInner).attr("stroke", darkGray).attr("fill", "none").attr("stroke-width", "1").style("pointer-events", "none");
    Xaxis.selectAll("empty").data(data.genonames).enter().append("text").text(function(d) {
      return d;
    }).attr("y", pad.top + hInner + pad.bottom * 0.3).attr("x", function(d, i) {
      return xScale(i);
    });
    Xaxis.append("text").text("genotype").attr("y", pad.top + hInner + pad.bottom * 0.7).attr("x", pad.left + wInner / 2).attr("fill", "blue");
    clicked = {};
    for (m in data.markers) {
      clicked[m] = 0;
    }
    jitterAmount = (xScale(1) - xScale(0)) / 6;
    jitter = [];
    for (i in data.geno) {
      jitter[i] = (2.0 * Math.random() - 1.0) * jitterAmount;
    }
    curMarker = data.markers[Math.floor(Math.random() * nmarkers)];
    console.log(curMarker);
    rightsvg.append("text").attr("id", "rightTitle").text(curMarker).attr("x", pad.left + wInner / 2).attr("y", pad.top / 2).attr("fill", "blue");
    mouseover = function(m) {
      if (!clicked[m]) {
        return d3.select(this).attr("fill", pink);
      }
    };
    mouseout = function(m) {
      if (!clicked[m]) {
        return d3.select(this).attr("fill", purple).attr("stroke", "none");
      }
    };
    click = function(m) {
      clicked[m] = 1;
      if (!(curMarker === "")) {
        clicked[curMarker] = 0;
        d3.select("#circle" + curMarker).attr("fill", purple).attr("stroke", "none");
      }
      d3.select(this).attr("fill", pink).attr("stroke", purple);
      d3.select("#rightTitle").text(m);
      curMarker = m;
      return rightdots.transition().duration(1000).attr("cx", function(d, i) {
        return xScale(data.geno[i][curMarker]) + jitter[i];
      });
    };
    markerdots = leftsvg.selectAll("empty").data(data.markers).enter().append("circle").attr("id", function(d) {
      return "circle" + d;
    }).attr("cx", pad.left + wLInner / 2 - 20).attr("cy", function(d, i) {
      return leftyScale(i);
    }).attr("r", 6).attr("fill", purple).attr("stroke", "none").attr("stroke-width", "2").on("mouseover", mouseover).on("mouseout", mouseout).on("click", click);
    leftsvg.selectAll("empty").data(data.markers).enter().append("text").text(function(d) {
      return d;
    }).attr("x", pad.left + wLInner / 2 + 20).attr("y", function(d, i) {
      return leftyScale(i);
    });
    clicked[curMarker] = 1;
    d3.select("#circle" + curMarker).attr("fill", pink).attr("stroke", purple);
    rightdots = rightsvg.selectAll("empty").data(data.pheno).enter().append("circle").attr("cx", function(d, i) {
      return xScale(data.geno[i][curMarker]) + jitter[i];
    }).attr("cy", function(d) {
      return yScale(d);
    }).attr("r", "4").attr("fill", darkGray).attr("stroke", "black").attr("stroke-width", "2");
    leftsvg.append("rect").attr("x", pad.left).attr("y", pad.top).attr("height", hInner).attr("width", wLInner).attr("class", "outerBox").style("pointer-events", "none");
    return rightsvg.append("rect").attr("x", pad.left).attr("y", pad.top).attr("height", hInner).attr("width", wInner).attr("class", "outerBox").style("pointer-events", "none");
  };

  d3.json("data.json", draw);

}).call(this);
