// Generated by CoffeeScript 1.6.3
(function() {
  var bgcolor, bigradius, circles, circles2touch, circolor, colors, dat, height, i, ncircles, nevents, print_event, radius, random_circles, ripples, svg, width, _i, _ref;

  width = 920;

  height = 450;

  ncircles = 20;

  colors = ["orchid", "#4DF0A7"];

  bgcolor = d3.rgb(200, 200, 200);

  radius = 8;

  bigradius = 16;

  svg = d3.select("div#chart").append("svg").attr({
    width: width,
    height: height
  });

  svg.append("rect").attr({
    x: 0,
    y: 0,
    width: width,
    height: height
  }).attr({
    "stroke-width": 5,
    stroke: "black",
    fill: bgcolor
  }).style("pointer-events", "none");

  random_circles = function(number, width, height) {
    var dat, i, _i;
    dat = [];
    for (i = _i = 0; 0 <= number ? _i < number : _i > number; i = 0 <= number ? ++_i : --_i) {
      dat.push([width, height].map(function(d) {
        return Math.floor(Math.random() * d);
      }));
    }
    return dat;
  };

  dat = random_circles(ncircles, width, height);

  circolor = [];

  for (i = _i = 0, _ref = dat.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    circolor[i] = colors[0];
  }

  circles2touch = svg.selectAll("empty").data(dat).enter().append("circle").attr("cx", function(d) {
    return d[0];
  }).attr("cy", function(d) {
    return d[1];
  }).attr({
    r: bigradius
  }).attr("opacity", 0).on("click", function(d, i) {
    print_event("circle click", [i, d[0], d[1]]);
    circolor[i] = circolor[i] === colors[0] ? colors[1] : colors[0];
    return svg.selectAll("#circ" + i).transition().ease("linear").duration(500).attr("fill", circolor[i]);
  });

  circles = svg.selectAll("empty").data(dat).enter().append("circle").attr("id", function(d, i) {
    return "circ" + i;
  }).attr("cx", function(d) {
    return d[0];
  }).attr("cy", function(d) {
    return d[1];
  }).attr({
    r: radius
  }).attr({
    stroke: "black",
    "stroke-width": 2,
    fill: colors[0]
  }).style("pointer-events", "none");

  ripples = function(position) {
    svg.append("circle").attr({
      cx: position[0],
      cy: position[1],
      r: 4
    }).attr({
      stroke: "slateblue",
      fill: "slateblue"
    }).style("pointer-events", "none").transition().delay(500).remove();
    return svg.selectAll("empty").data([0, 1, 2, 3, 4]).enter().append("circle").attr({
      cx: position[0],
      cy: position[1],
      r: 0
    }).attr({
      stroke: "slateblue",
      "stroke-width": 2,
      fill: "none"
    }).style({
      opacity: 1
    }).style("pointer-events", "none").transition().ease("linear").duration(500).delay(function(d) {
      return d * 50;
    }).attr("r", 100).style("opacity", 0).remove();
  };

  nevents = 0;

  svg.on("click", function() {
    var event;
    event = d3.mouse(this);
    ripples(event);
    return print_event("click", event);
  });

  print_event = function(type, location) {
    nevents++;
    return d3.select("div#console").append("p").text("" + type + " " + nevents + " : " + location);
  };

}).call(this);
