// Generated by CoffeeScript 1.4.0
(function() {
  var draw;

  draw = function(data) {
    var altpink, avePhe, botAxes, botyTicks, clickColors, clickCurve, clicked, colorseq, curInd, curve, darkBlue, darkGray, darkRed, dif, difdown, drawCurve, h, i, image, imgPixels, indexInd, j, labelcolor, lightGray, maincolor, maxPhe, minPhe, nInd, nTimes, n_colors, nodig, onedig, orderedInd, pad, phe, phecurve, phenoList, pink, pixelsPer, purple, randomInd, redblue, svg, titlecolor, topAxes, topyTicks, totalh, totalw, twodig, w, xPos, xScaleCurve, xScaleImg, xTicks, xloc, yScaleCurve, yScaleImg, yVals, yloc, zScaleImg, _i, _j, _k, _l, _len, _len1, _ref, _ref1, _results, _results1;
    d3.select("p#loading").remove();
    d3.select("div#legend").style("opacity", 1);
    darkBlue = "darkslateblue";
    lightGray = d3.rgb(230, 230, 230);
    darkGray = d3.rgb(200, 200, 200);
    pink = "hotpink";
    altpink = "#E9CFEC";
    purple = "#8C4374";
    darkRed = "crimson";
    labelcolor = "black";
    titlecolor = "blue";
    maincolor = "blue";
    nodig = d3.format(".0f");
    onedig = d3.format(".1f");
    twodig = d3.format(".2f");
    nTimes = data.times.length;
    nInd = data.curves.length;
    phenoList = [];
    minPhe = 999;
    maxPhe = -999;
    avePhe = [];
    for (i in data.curves) {
      avePhe[i] = 0;
      for (j in data.curves[i]) {
        phe = data.curves[i][j];
        avePhe[i] += phe;
        phenoList.push({
          row: i,
          col: j,
          value: phe
        });
        if (minPhe > phe) {
          minPhe = phe;
        }
        if (maxPhe < phe) {
          maxPhe = phe;
        }
      }
      avePhe[i] /= nTimes;
    }
    orderedInd = d3.range(nInd).sort(function(a, b) {
      if (avePhe[a] < avePhe[b]) {
        return -1;
      }
      if (avePhe[b] < avePhe[a]) {
        return +1;
      }
      return 0;
    });
    indexInd = orderedInd.slice(0);
    for (i in orderedInd) {
      indexInd[orderedInd[i]] = i;
    }
    pixelsPer = 3;
    w = nTimes * pixelsPer;
    h = [nInd * pixelsPer, 200];
    pad = {
      left: 60,
      top: 15,
      right: 25,
      bottom: 40,
      inner: 0
    };
    totalw = w + pad.left + pad.right;
    totalh = h[0] + h[1] + pad.top * 2 + pad.bottom * 2;
    svg = d3.select("div#curvesfig").append("svg").attr("height", totalh).attr("width", totalw);
    image = svg.append("g").attr("id", "imagepanel").attr("transform", "translate(" + pad.left + "," + pad.top + ")");
    curve = svg.append("g").attr("id", "curvepanel").attr("transform", "translate(" + pad.left + "," + (pad.top * 2 + pad.bottom + h[0]) + ")");
    image.append("rect").attr("height", h[0]).attr("width", w).attr("fill", "white").attr("stroke", "black").attr("stroke-width", 1);
    curve.append("rect").attr("height", h[1]).attr("width", w).attr("fill", lightGray).attr("stroke", "black").attr("stroke-width", 1);
    xScaleImg = d3.scale.ordinal().domain(d3.range(nTimes)).rangePoints([0, pixelsPer * (nTimes - 1) + 1], 0);
    yScaleImg = d3.scale.ordinal().domain(d3.range(nInd)).rangePoints([0, pixelsPer * (nInd - 1) + 1], 0);
    dif = maxPhe + 45;
    difdown = -45 - minPhe;
    if (dif < difdown) {
      dif = difdown;
    }
    n_colors = 128;
    colorseq = (function() {
      _results = [];
      for (var _i = 0; 0 <= n_colors ? _i <= n_colors : _i >= n_colors; 0 <= n_colors ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    for (i in colorseq) {
      colorseq[i] /= n_colors;
    }
    redblue = [];
    for (_j = 0, _len = colorseq.length; _j < _len; _j++) {
      i = colorseq[_j];
      redblue.push(d3.interpolateRgb("#2166ac", "#f7f7f7")(i));
    }
    _ref = colorseq.slice(1);
    for (_k = 0, _len1 = _ref.length; _k < _len1; _k++) {
      i = _ref[_k];
      redblue.push(d3.interpolateRgb("#f7f7f7", "#b2182b")(i));
    }
    zScaleImg = d3.scale.quantile().domain([-45 - dif, -45 + dif]).range(redblue);
    xScaleCurve = d3.scale.linear().domain([0, d3.max(data.times)]).range([pixelsPer / 2, w - pixelsPer / 2]);
    yScaleCurve = d3.scale.linear().domain([minPhe, maxPhe]).range([h[1] - pad.inner, pad.inner]);
    xTicks = [0, 1, 2, 3, 4, 5, 6, 7, 8];
    topAxes = image.append("g").attr("id", "topAxes").attr("pointer-events", "none");
    topAxes.selectAll("empty").data(xTicks).enter().append("line").attr("x1", function(d) {
      return xScaleImg(d * 30 - 1) + pixelsPer / 2;
    }).attr("x2", function(d) {
      return xScaleImg(d * 30 - 1) + pixelsPer / 2;
    }).attr("y1", h[0]).attr("y2", h[0] + pad.bottom * 0.1).attr("stroke", labelcolor);
    topAxes.selectAll("empty").data(xTicks).enter().append("text").text(function(d) {
      return d;
    }).attr("x", function(d) {
      return xScaleImg(d * 30 - 1) + pixelsPer / 2;
    }).attr("y", h[0] + pad.bottom * 0.2).attr("fill", labelcolor).attr("text-anchor", "middle").attr("dominant-baseline", "hanging");
    topAxes.append("text").attr("x", w / 2).attr("y", h[0] + pad.bottom * 0.75).text("Time (hours)").attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "hanging");
    topyTicks = [49, 99, 149];
    topAxes.selectAll("empty").data(topyTicks).enter().append("line").attr("x1", 0).attr("x2", -pad.left * 0.1).attr("y1", function(d) {
      return yScaleImg(d);
    }).attr("y2", function(d) {
      return yScaleImg(d);
    }).attr("stroke", labelcolor);
    topAxes.selectAll("empty").data(topyTicks).enter().append("text").text(function(d) {
      return d * 1 + 1;
    }).attr("x", -pad.left * 0.2).attr("y", function(d) {
      return yScaleImg(d);
    }).attr("fill", labelcolor).attr("text-anchor", "end").attr("dominant-baseline", "middle");
    xloc = -pad.left * 0.75;
    yloc = h[0] / 2;
    topAxes.append("text").attr("x", xloc).attr("y", yloc).text("Lines (sorted)").attr("fill", titlecolor).attr("text-anchor", "middle").attr("transform", "rotate(270," + xloc + "," + yloc + ")");
    botAxes = curve.append("g").attr("id", "botAxes").attr("pointer-events", "none");
    botAxes.selectAll("empty").data(xTicks).enter().append("line").attr("x1", function(d) {
      return xScaleCurve(d * 60);
    }).attr("x2", function(d) {
      return xScaleCurve(d * 60);
    }).attr("y1", h[1]).attr("y2", 0).attr("stroke", "white");
    botAxes.selectAll("empty").data(xTicks).enter().append("text").text(function(d) {
      return d;
    }).attr("x", function(d) {
      return xScaleCurve(d * 60);
    }).attr("y", h[1] + pad.bottom * 0.1).attr("fill", labelcolor).attr("text-anchor", "middle").attr("dominant-baseline", "hanging");
    botAxes.append("text").attr("x", w / 2).attr("y", h[1] + pad.bottom * 0.65).text("Time (hours)").attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "hanging");
    botyTicks = yScaleCurve.ticks(5);
    botAxes.selectAll("empty").data(botyTicks).enter().append("line").attr("x1", 0).attr("x2", w).attr("y1", function(d) {
      return yScaleCurve(d);
    }).attr("y2", function(d) {
      return yScaleCurve(d);
    }).attr("stroke", "white");
    botAxes.selectAll("empty").data(botyTicks).enter().append("text").text(function(d) {
      return d;
    }).attr("x", -pad.left * 0.1).attr("y", function(d) {
      return yScaleCurve(d);
    }).attr("fill", labelcolor).attr("text-anchor", "end").attr("dominant-baseline", "middle");
    xloc = -pad.left * 0.65;
    yloc = h[1] / 2;
    botAxes.append("text").attr("x", xloc).attr("y", yloc).text("Phenotype").attr("fill", titlecolor).attr("text-anchor", "middle").attr("transform", "rotate(270," + xloc + "," + yloc + ")");
    clicked = [];
    for (i in orderedInd) {
      clicked[i] = false;
    }
    imgPixels = image.append("g").attr("id", "imgPixels").selectAll("rect").data(phenoList).enter().append("rect").attr("class", "imgPixels").attr("x", function(d) {
      return xScaleImg(d.col);
    }).attr("y", function(d) {
      return yScaleImg(indexInd[d.row]);
    }).attr("height", pixelsPer).attr("width", pixelsPer).attr("fill", function(d) {
      return zScaleImg(d.value);
    }).attr("stroke", function(d) {
      return zScaleImg(d.value);
    }).attr("stroke-width", 0.5).on("mouseover", function(d) {
      return drawCurve(d.row);
    }).on("click", function(d) {
      return clickCurve(d.row);
    });
    phecurve = function(ind) {
      return d3.svg.line().x(function(d) {
        return xScaleCurve(d);
      }).y(function(d, di) {
        return yScaleCurve(data.curves[ind][di]);
      });
    };
    drawCurve = function(ind) {
      var curInd, thecurve;
      if (ind === curInd) {
        return 0;
      }
      curInd = ind;
      d3.select("g#phecurve").remove();
      thecurve = curve.append("g").attr("id", "phecurve");
      thecurve.append("path").attr("id", "phecurve").datum(data.times).attr("d", phecurve(ind)).attr("stroke", darkBlue).attr("fill", "none").attr("stroke-width", "2");
      return thecurve.append("text").datum(ind).text("line " + (ind * 1 + 1)).attr("x", xScaleCurve(7 * 60 + 10)).attr("y", (yScaleCurve(0) + yScaleCurve(-20)) / 2).attr("text-anchor", "start").attr("fill", darkBlue).attr("dominant-baseline", "middle");
    };
    clickColors = ["blue", "red", "green", "orange", "black"];
    clickCurve = function(ind) {
      var curcolor, thecurve;
      if (clicked[ind]) {
        clicked[ind] = false;
        d3.select("g#phecurve_" + ind).remove();
        d3.select("rect#pherect_" + ind).remove();
        return drawCurve(ind);
      } else {
        d3.select("path#phecurve").remove();
        curcolor = clickColors.shift();
        clickColors.push(curcolor);
        clicked[ind] = true;
        thecurve = curve.append("g").attr("id", "phecurve_" + ind);
        thecurve.append("path").datum(data.times).attr("d", phecurve(ind)).attr("stroke", curcolor).attr("fill", "none").attr("stroke-width", 2);
        return image.append("rect").attr("id", "pherect_" + ind).attr("x", 0).attr("width", w).attr("y", yScaleImg(indexInd[ind])).attr("height", pixelsPer).attr("fill", "none").attr("stroke", curcolor).attr("stroke-width", 1).attr("pointer-events", "none");
      }
    };
    randomInd = Math.floor(Math.random() * nInd);
    drawCurve(randomInd);
    curInd = randomInd;
    yVals = (function() {
      _results1 = [];
      for (var _l = 0, _ref1 = h[1]; 0 <= _ref1 ? _l < _ref1 : _l > _ref1; 0 <= _ref1 ? _l++ : _l--){ _results1.push(_l); }
      return _results1;
    }).apply(this);
    for (i in yVals) {
      yVals[i] = minPhe + (maxPhe - minPhe) * i / h[1];
    }
    xPos = w + 10;
    return curve.append("g").attr("id", "colorscale").selectAll("empty").data(yVals).enter().append("rect").attr("x", xPos).attr("width", pad.right - 10).attr("y", function(d) {
      return yScaleCurve(d);
    }).attr("height", 1).attr("fill", function(d) {
      return zScaleImg(d);
    }).attr("stroke", function(d) {
      return zScaleImg(d);
    }).attr("stroke-width", 0.5);
  };

  d3.json("curves.json", draw);

}).call(this);
