// Generated by CoffeeScript 1.12.6
(function() {
  var button_size, color, gap, height, hilit, i, left_width, make_plot, margin, myscatter, rad, sets, svg, width, y;

  height = 500;

  width = 800;

  left_width = 80;

  gap = 10;

  button_size = 20;

  rad = 3;

  color = "#6A5ACD";

  hilit = "#C71585";

  margin = {
    left: 60,
    top: 40,
    right: 40,
    bottom: 40,
    inner: 5
  };

  svg = d3.select("div#chart").append("svg").attr("height", height).attr("width", width + left_width);

  sets = ["I", "II", "III", "IV"];

  y = (function() {
    var results;
    results = [];
    for (i in sets) {
      results.push(margin.top + i * button_size * 1.5);
    }
    return results;
  })();

  svg.selectAll("empty").data(sets).enter().append("rect").attr("x", gap).attr("y", function(d, i) {
    return y[i];
  }).attr("height", button_size).attr("width", button_size).attr("fill", color).on("mouseover", function(d) {
    return d3.select(this).attr("fill", hilit);
  }).on("mouseout", function(d) {
    return d3.select(this).attr("fill", color);
  }).on("click", function(d) {
    return make_plot(d);
  });

  svg.selectAll("empty").data(sets).enter().append("text").text(function(d) {
    return d;
  }).attr("x", gap + button_size * 2).attr("y", function(d, i) {
    return y[i] + button_size / 2.0;
  }).style("dominant-baseline", "middle").style("text-anchor", "middle").style("font-size", "20px");

  myscatter = d3panels.scatterplot({
    margin: margin,
    xlim: [3, 20],
    ylim: [2.1, 13.74],
    xlab: "X",
    ylab: "Y",
    height: height,
    width: width,
    pointsize: rad,
    pointcolor: color
  });

  make_plot = function(set) {
    return d3.json("http://localhost:8080/anscombe/" + set, function(data) {
      var d, data4plot, myscatter_svg;
      data4plot = {
        x: (function() {
          var j, len, ref, results;
          ref = data.data;
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            d = ref[j];
            results.push(d.x);
          }
          return results;
        })(),
        y: (function() {
          var j, len, ref, results;
          ref = data.data;
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            d = ref[j];
            results.push(d.y);
          }
          return results;
        })()
      };
      d3.select("svg#scatterplot").remove();
      d3.select(".d3-tip").remove();
      myscatter_svg = svg.append("svg").attr("height", height).attr("width", width + left_width).attr("id", "scatterplot").append("g").attr("transform", "translate(" + left_width + ",0)");
      return myscatter(myscatter_svg, data4plot);
    });
  };

}).call(this);
