// Generated by CoffeeScript 1.12.5
var slider;

slider = function(chartOpts) {
  var buttoncolor, buttondotfill, buttondotsize, buttonround, buttonsize, buttonstroke, chart, height, margin, nticks, rectcolor, rectheight, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, slider_svg, textsize, tickgap, tickheight, ticks, value, width;
  if (chartOpts == null) {
    chartOpts = {};
  }
  width = (ref = chartOpts != null ? chartOpts.width : void 0) != null ? ref : 800;
  height = (ref1 = chartOpts != null ? chartOpts.height : void 0) != null ? ref1 : 80;
  margin = (ref2 = chartOpts != null ? chartOpts.margin : void 0) != null ? ref2 : 25;
  rectheight = (ref3 = chartOpts != null ? chartOpts.rectheight : void 0) != null ? ref3 : 10;
  rectcolor = (ref4 = chartOpts != null ? chartOpts.rectcolor : void 0) != null ? ref4 : "#ccc";
  buttonsize = (ref5 = chartOpts != null ? chartOpts.buttonsize : void 0) != null ? ref5 : rectheight * 2;
  buttoncolor = (ref6 = chartOpts != null ? chartOpts.buttoncolor : void 0) != null ? ref6 : "#eee";
  buttonstroke = (ref7 = chartOpts != null ? chartOpts.buttonstroke : void 0) != null ? ref7 : "black";
  buttonround = (ref8 = chartOpts != null ? chartOpts.buttonround : void 0) != null ? ref8 : buttonsize * 0.2;
  buttondotfill = (ref9 = chartOpts != null ? chartOpts.buttondotfill : void 0) != null ? ref9 : "slateblue";
  buttondotsize = (ref10 = chartOpts != null ? chartOpts.buttondotsize : void 0) != null ? ref10 : buttonsize / 4;
  tickheight = (ref11 = chartOpts != null ? chartOpts.tickheight : void 0) != null ? ref11 : 10;
  tickgap = (ref12 = chartOpts != null ? chartOpts.tickgap : void 0) != null ? ref12 : tickheight / 2;
  textsize = (ref13 = chartOpts != null ? chartOpts.textsize : void 0) != null ? ref13 : 14;
  nticks = (ref14 = chartOpts != null ? chartOpts.nticks : void 0) != null ? ref14 : 5;
  ticks = (ref15 = chartOpts != null ? chartOpts.ticks : void 0) != null ? ref15 : null;
  value = 0;
  slider_svg = null;
  chart = function(selection, callback, range, stops) {
    var button, clamp_pixels, dragged, xscale;
    if (range == null) {
      range = [margin, width - margin * 2];
    }
    value = (range[1] - range[0]) * Math.random() + range[0];
    slider_svg = selection.insert("svg").attr("height", height).attr("width", width);
    xscale = d3.scaleLinear().range([margin, width - margin]).domain(range).clamp(true);
    clamp_pixels = function(pixels, interval) {
      if (pixels < interval[0]) {
        return interval[0];
      }
      if (pixels > interval[1]) {
        return interval[1];
      }
      return pixels;
    };
    slider_svg.insert("rect").attr("x", margin).attr("y", height / 2 - rectheight / 2).attr("rx", rectheight * 0.3).attr("ry", rectheight * 0.3).attr("width", width - margin * 2).attr("height", rectheight).attr("fill", rectcolor);
    if (ticks == null) {
      ticks = xscale.ticks(nticks);
    }
    slider_svg.selectAll("empty").data(ticks).enter().insert("line").attr("x1", function(d) {
      return xscale(d);
    }).attr("x2", function(d) {
      return xscale(d);
    }).attr("y1", height / 2 + rectheight / 2 + tickgap).attr("y2", height / 2 + rectheight / 2 + tickgap + tickheight).attr("stroke", "black").attr("shape-rendering", "crispEdges");
    slider_svg.selectAll("empty").data(ticks).enter().insert("text").attr("x", function(d) {
      return xscale(d);
    }).attr("y", height / 2 + rectheight / 2 + tickgap * 2 + tickheight).text(function(d) {
      return d;
    }).style("font-size", textsize).style("dominant-baseline", "hanging").style("text-anchor", "middle").style("pointer-events", "none");
    button = slider_svg.insert("g").attr("id", "button").attr("transform", "translate(" + xscale(value) + ",0)");
    button.insert("rect").attr("x", -buttonsize / 2).attr("y", height / 2 - buttonsize / 2).attr("height", buttonsize).attr("width", buttonsize).attr("rx", buttonround).attr("ry", buttonround).attr("stroke", buttonstroke).attr("stroke-width", 2).attr("fill", buttoncolor);
    button.insert("circle").attr("cx", 0).attr("cy", height / 2).attr("r", buttondotsize).attr("fill", buttondotfill);
    dragged = function(d) {
      var clamped_pixels, pixel_value;
      pixel_value = d3.event.x - margin;
      clamped_pixels = clamp_pixels(pixel_value, [0, width - margin * 2]);
      value = xscale.invert(clamped_pixels + margin);
      if (callback != null) {
        callback(chart);
      }
      return d3.select(this).attr("transform", "translate(" + xscale(value) + ",0)");
    };
    button.call(d3.drag().on("drag", dragged));
    if (callback != null) {
      return callback(chart);
    }
  };
  chart.value = function(arg) {
    if (arg != null) {
      value = arg;
    }
    return value;
  };
  chart.remove = function() {
    return slider_svg.remove();
  };
  return chart;
};
