// Generated by CoffeeScript 1.8.0
var canvasApp;

canvasApp = function() {
  var anyOverlap, check4collisions, circles, collide, colors, context, createCircle, distance, drawCircle, drawScreen, first_red, gameLoop, h, hitWall, i, n_circles, num_white, pad, rad, stop, theCanvas, updateCircle, w, _i;
  w = 800;
  h = 800;
  rad = 5;
  pad = 2 * rad;
  d3.select("div.canvas").append("canvas").attr("id", "canvasOne").attr("width", w).attr("height", h);
  theCanvas = d3.select("canvas#canvasOne");
  context = theCanvas.node().getContext("2d");
  colors = ["#fff", "#FF4136"];
  createCircle = function() {
    var circ;
    circ = {
      x: pad + Math.random() * (w - 2 * pad),
      y: pad + Math.random() * (h - 2 * pad),
      r: rad,
      speed: 1,
      angle: Math.random() * 2 * Math.PI
    };
    if (anyOverlap(circ, circles)) {
      circ = createCircle();
    }
    circ = updateCircle(circ);
    circ.color_index = 0;
    return circ;
  };
  distance = function(circ1, circ2) {
    return Math.sqrt(Math.pow(circ1.x - circ2.x, 2) + Math.pow(circ1.y - circ2.y, 2));
  };
  anyOverlap = function(circ, circles) {
    var other, _i, _len;
    for (_i = 0, _len = circles.length; _i < _len; _i++) {
      other = circles[_i];
      if (distance(circ, other) <= 10) {
        console.log(distance(circ, other));
      }
      if (distance(circ, other) <= circ.r + other.r + pad) {
        return true;
      }
    }
    return false;
  };
  updateCircle = function(circ) {
    circ.velo_x = circ.speed * Math.cos(circ.angle);
    circ.velo_y = circ.speed * Math.sin(circ.angle);
    return circ;
  };
  n_circles = 200;
  circles = [];
  for (i = _i = 1; 1 <= n_circles ? _i <= n_circles : _i >= n_circles; i = 1 <= n_circles ? ++_i : --_i) {
    circles.push(createCircle());
  }
  circles[0].color_index = 1;
  first_red = 0;
  num_white = function() {
    var circ, count_white, _j, _len;
    count_white = 0;
    for (_j = 0, _len = circles.length; _j < _len; _j++) {
      circ = circles[_j];
      if (circ.color_index === 0) {
        ++count_white;
      }
    }
    return count_white;
  };
  hitWall = function(circ) {
    if (circ.x > w - circ.r || circ.x < circ.r) {
      circ.angle = Math.PI - circ.angle;
      circ = updateCircle(circ);
    }
    if (circ.y > h - circ.r || circ.y < circ.r) {
      circ.angle = 2 * Math.PI - circ.angle;
      circ = updateCircle(circ);
    }
    return circ;
  };
  check4collisions = function() {
    var d, j, _j, _ref, _results;
    _results = [];
    for (i = _j = 0, _ref = circles.length - 1; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      _results.push((function() {
        var _k, _ref1, _ref2, _results1;
        _results1 = [];
        for (j = _k = _ref1 = i + 1, _ref2 = circles.length; _ref1 <= _ref2 ? _k < _ref2 : _k > _ref2; j = _ref1 <= _ref2 ? ++_k : --_k) {
          d = distance(circles[i], circles[j]);
          if (d <= circles[i].r + circles[j].r) {
            _results1.push(collide(i, j));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };
  collide = function(i, j) {
    var ball1, ball2, dx, dy, phi, velox_1, velox_2, veloy_1, veloy_2;
    ball1 = circles[i];
    ball2 = circles[j];
    if (ball1.color_index + ball2.color_index > 0) {
      ball1.color_index = 1;
      ball2.color_index = 1;
    }
    dx = ball1.x - ball2.x;
    dy = ball1.y - ball2.y;
    phi = Math.atan2(dy, dx);
    velox_1 = ball2.speed * Math.cos(ball2.angle - phi) * Math.cos(phi) + ball1.speed * Math.sin(ball1.angle - phi) * Math.cos(phi + Math.PI / 2);
    veloy_1 = ball2.speed * Math.cos(ball2.angle - phi) * Math.sin(phi) + ball1.speed * Math.sin(ball1.angle - phi) * Math.sin(phi + Math.PI / 2);
    velox_2 = ball1.speed * Math.cos(ball1.angle - phi) * Math.cos(phi) + ball2.speed * Math.sin(ball2.angle - phi) * Math.cos(phi + Math.PI / 2);
    veloy_2 = ball1.speed * Math.cos(ball1.angle - phi) * Math.sin(phi) + ball2.speed * Math.sin(ball2.angle - phi) * Math.sin(phi + Math.PI / 2);
    ball1.angle = Math.atan2(veloy_1, velox_1);
    ball2.angle = Math.atan2(veloy_2, velox_2);
    ball1.speed = Math.sqrt(Math.pow(velox_1, 2) + Math.pow(veloy_1, 2));
    ball2.speed = Math.sqrt(Math.pow(velox_2, 2) + Math.pow(veloy_2, 2));
    circles[i] = updateCircle(ball1);
    return circles[j] = updateCircle(ball2);
  };
  drawCircle = function(circ) {
    context.fillStyle = colors[circ.color_index];
    context.lineWidth = 2;
    context.beginPath();
    context.arc(circ.x, circ.y, circ.r, 0, 2 * Math.PI, false);
    context.closePath();
    context.stroke();
    context.fill();
    circ = hitWall(circ);
    circ.x += circ.velo_x;
    circ.y += circ.velo_y;
    return circ;
  };
  drawScreen = function() {
    var num_left, _j, _k, _ref, _ref1, _results;
    context.fillStyle = "#111";
    context.strokeStyle = "#111";
    context.lineWidth = 4;
    context.fillRect(0, 0, w, h);
    context.strokeRect(0, 0, w, h);
    check4collisions();
    for (i = _j = 0, _ref = circles.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      circles[i] = drawCircle(circles[i]);
    }
    num_left = num_white();
    if (num_left > 1) {
      if (num_left > 1) {
        return d3.select("p#message").text("First red = " + first_red + "; number of white left = " + num_left);
      }
    } else if (num_left === 1) {
      _results = [];
      for (i = _k = 0, _ref1 = circles.length; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; i = 0 <= _ref1 ? ++_k : --_k) {
        if (circles[i].color_index === 0) {
          first_red = i;
        }
        _results.push(circles[i].color_index = 1 - circles[i].color_index);
      }
      return _results;
    }
  };
  stop = false;
  gameLoop = function() {
    document.onkeydown = function(e) {
      var keypress;
      keypress = String.fromCharCode(e.keyCode).toLowerCase();
      if (keypress === "r") {
        console.log("reverse");
        return circles = circles.map(function(circ) {
          circ.angle = circ.angle + Math.PI;
          return updateCircle(circ);
        });
      } else if (stop) {
        console.log("start");
        stop = false;
        return gameLoop();
      } else {
        console.log("stop");
        return stop = true;
      }
    };
    if (!stop) {
      window.setTimeout(gameLoop, 2);
    }
    return drawScreen();
  };
  return gameLoop();
};

window.onload = canvasApp;
