// Generated by CoffeeScript 1.9.0
(function() {
  var buttons, gap, generate_point, h, h_button, n, note, points, points_last, rect, svg, update, w, w_button;

  w = 960;

  h = 500;

  h_button = 50;

  w_button = 120;

  gap = 25;

  svg = d3.select("div#figure").append("svg").attr("height", h + gap + h_button).attr("width", w);

  rect = svg.append("rect").attr("height", h).attr("width", w).attr("class", "background");

  buttons = svg.selectAll("empty").data([0, 1]).enter().append("rect").attr("x", function(d) {
    return gap + (w_button + gap) * d;
  }).attr("y", function(d) {
    return h + gap;
  }).attr("height", h_button).attr("width", w_button).attr("class", "button");

  svg.selectAll("empty").data([0, 1]).enter().append("text").attr("class", "button").attr("x", function(d) {
    return gap + (w_button + gap) * d + w_button / 2;
  }).attr("y", function(d) {
    return h + gap + h_button / 2;
  }).text(function(d) {
    return ["birth", "death"][d];
  });

  note = svg.append("text").attr("x", 20).attr("y", 20);

  n = 4;

  generate_point = function(i) {
    return {
      x: Math.random() * w,
      y: Math.random() * h,
      id: i
    };
  };

  points = d3.range(n).map(function(i) {
    return generate_point(i);
  });

  points_last = n - 1;

  update = function(data, time) {
    var circles;
    if (time == null) {
      time = 1000;
    }
    circles = svg.selectAll("circle.points").data(data, function(d) {
      return d.id;
    }).attr("cx", function(d) {
      return d.x;
    }).attr("cy", function(d) {
      return d.y;
    }).attr("r", 10).attr("class", "points");
    circles.enter().append("circle").attr("cx", function(d) {
      return d.x;
    }).attr("cy", function(d) {
      return d.y;
    }).attr("r", 0).attr("class", "points").transition().duration(time).attr("r", 10);
    return circles.exit().classed({
      "dead": true
    }).transition().duration(time / 2).delay(time / 2).attr("r", 0).remove();
  };

  update(points);

  buttons.on("click", function(d) {
    var to_die;
    if (d === 1 && points.length > 0) {
      to_die = Math.floor(Math.random() * points.length);
      note.text("death to number " + (points[to_die].id + 1));
      points.splice(to_die - 1, 1);
    } else if (d === 0) {
      points_last += 1;
      points.push(generate_point(points_last));
      note.text("birth to number " + points_last);
    }
    return update(points);
  });

}).call(this);
