// Generated by CoffeeScript 1.8.0
var height, i, n_points, point_color, point_radius, points, rect_color, svg, width, _i;

height = 500;

width = 500;

n_points = 30;

rect_color = "#bbb";

point_color = "slateblue";

point_radius = 5;

svg = d3.select("div#chart").append("svg").attr("height", height).attr("width", width);

svg.append("rect").attr("x", 0).attr("y", 0).attr("height", height).attr("width", width).attr("fill", rect_color).attr("stroke", "black");

points = [];

for (i = _i = 1; 1 <= n_points ? _i <= n_points : _i >= n_points; i = 1 <= n_points ? ++_i : --_i) {
  points.push({
    x: Math.random() * width,
    y: Math.random() * height
  });
}

svg.selectAll("empty").data(points).enter().append("circle").attr("cx", function(d) {
  return d.x;
}).attr("cy", function(d) {
  return d.y;
}).attr("r", point_radius).attr("fill", point_color).attr("stroke", "black").attr("class", "points");

d3.select("input[type=range]#opacity").on("input", function() {
  var opacity;
  opacity = this.value;
  d3.select("output#opacity").text(d3.format(".2f")(opacity));
  return d3.selectAll("circle.points").attr("opacity", opacity);
});
