// Generated by CoffeeScript 1.8.0
var circles, createCircle, h, i, n_circles, svg, w, _i;

w = 800;

h = 800;

d3.selection.prototype.moveToFront = function() {
  return this.each(function() {
    return this.parentNode.appendChild(this);
  });
};

svg = d3.select("div#chart").append("svg").attr("width", w).attr("height", h);

svg.append("rect").attr("height", h).attr("width", w).attr("stroke", "black").attr("stroke-width", 2).attr("fill", "#bbb");

createCircle = function() {
  var circ;
  circ = {
    r: Math.random() * 3 + 3
  };
  circ.x = circ.r + Math.random() * (w - circ.r * 2);
  circ.y = circ.r + Math.random() * (h - circ.r * 2);
  return circ;
};

n_circles = 100000;

circles = [];

for (i = _i = 1; 1 <= n_circles ? _i <= n_circles : _i >= n_circles; i = 1 <= n_circles ? ++_i : --_i) {
  circles.push(createCircle());
}

svg.selectAll("empty").data(circles).enter().append("circle").attr("cx", function(d) {
  return d.x;
}).attr("cy", function(d) {
  return d.y;
}).attr("r", function(d) {
  return d.r;
}).attr("stroke", "black").attr("fill", "slateblue").attr("stroke-width", 1).on("mouseover", function() {
  return d3.select(this).attr("fill", "Orchid").moveToFront();
}).on("mouseout", function() {
  return d3.select(this).attr("fill", "slateblue");
});
