// Generated by CoffeeScript 1.8.0
var canvasApp;

canvasApp = function() {
  var anyOverlap, check4collisions, check4deaths, circ_rad, circ_speed, circles, cleanShots, collide, collided, colors, context, createCircle, createShot, delay, distance, drawCircle, drawScreen, drawShot, first_red, gameLoop, h, hitWall, i, n_circles, num_white, pad, pr_shot, shot_rad, shot_speed, shots, stop, theCanvas, updateCircle, w, _i;
  w = 960;
  h = 960;
  n_circles = 100;
  circ_rad = 5;
  circ_speed = 1;
  pr_shot = 0.0005;
  shot_rad = 2;
  shot_speed = 5;
  pad = 2 * circ_rad;
  delay = 10;
  d3.select("div.canvas").append("canvas").attr("id", "canvasOne").attr("width", w).attr("height", h);
  theCanvas = d3.select("canvas#canvasOne");
  context = theCanvas.node().getContext("2d");
  colors = ["#fff", "#FF4136"];
  createCircle = function(x, y, r, speed) {
    var circ;
    if (x == null) {
      x = null;
    }
    if (y == null) {
      y = null;
    }
    if (r == null) {
      r = null;
    }
    if (speed == null) {
      speed = null;
    }
    circ = {
      x: pad + Math.random() * (w - 2 * pad),
      y: pad + Math.random() * (h - 2 * pad),
      r: circ_rad,
      speed: circ_speed,
      angle: Math.random() * 2 * Math.PI
    };
    if (anyOverlap(circ, circles)) {
      circ = createCircle();
    }
    circ = updateCircle(circ);
    circ.color_index = 0;
    return circ;
  };
  createShot = function(x, y) {
    var circ;
    circ = {
      x: x,
      y: y,
      r: shot_rad,
      speed: circ_rad + 1,
      angle: Math.random() * 2 * Math.PI
    };
    circ = updateCircle(circ);
    circ.x += circ.velo_x;
    circ.y += circ.velo_y;
    circ.speed = shot_speed;
    circ = updateCircle(circ);
    circ.color_index = 0;
    return circ;
  };
  distance = function(circ1, circ2) {
    return Math.sqrt(Math.pow(circ1.x - circ2.x, 2) + Math.pow(circ1.y - circ2.y, 2));
  };
  anyOverlap = function(circ, circles) {
    var other, _i, _len;
    for (_i = 0, _len = circles.length; _i < _len; _i++) {
      other = circles[_i];
      if (distance(circ, other) <= circ.r + other.r + pad) {
        return true;
      }
    }
    return false;
  };
  updateCircle = function(circ) {
    circ.velo_x = circ.speed * Math.cos(circ.angle);
    circ.velo_y = circ.speed * Math.sin(circ.angle);
    return circ;
  };
  circles = [];
  for (i = _i = 1; 1 <= n_circles ? _i <= n_circles : _i >= n_circles; i = 1 <= n_circles ? ++_i : --_i) {
    circles.push(createCircle());
  }
  circles[0].color_index = 1;
  first_red = 0;
  shots = [];
  num_white = function() {
    var circ, count_white, _j, _len;
    count_white = 0;
    for (_j = 0, _len = circles.length; _j < _len; _j++) {
      circ = circles[_j];
      if (circ.color_index === 0) {
        ++count_white;
      }
    }
    return count_white;
  };
  hitWall = function(circ) {
    if (circ.x > w - circ.r || circ.x < circ.r) {
      circ.angle = Math.PI - circ.angle;
      circ = updateCircle(circ);
    }
    if (circ.y > h - circ.r || circ.y < circ.r) {
      circ.angle = 2 * Math.PI - circ.angle;
      circ = updateCircle(circ);
    }
    return circ;
  };
  cleanShots = function() {
    var shot;
    shots = (function() {
      var _j, _len, _results;
      _results = [];
      for (_j = 0, _len = shots.length; _j < _len; _j++) {
        shot = shots[_j];
        if (shot.x < w && shot.x > 0 && shot.y < h && shot.y > 0) {
          _results.push(shot);
        }
      }
      return _results;
    })();
    if (shots == null) {
      return shots = [];
    }
  };
  collided = function(circ1, circ2) {
    return distance(circ1, circ2) <= circ1.r + circ2.r;
  };
  check4collisions = function() {
    var j, _j, _ref, _results;
    _results = [];
    for (i = _j = 0, _ref = circles.length - 1; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      _results.push((function() {
        var _k, _ref1, _ref2, _results1;
        _results1 = [];
        for (j = _k = _ref1 = i + 1, _ref2 = circles.length; _ref1 <= _ref2 ? _k < _ref2 : _k > _ref2; j = _ref1 <= _ref2 ? ++_k : --_k) {
          if (collided(circles[i], circles[j])) {
            _results1.push(collide(i, j));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };
  check4deaths = function() {
    var delete_circ, delete_shot, j, v, _j, _k, _l, _len, _len1, _m, _ref, _ref1, _ref2, _ref3, _results;
    delete_circ = [];
    delete_shot = [];
    for (i = _j = 0, _ref = circles.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      for (j = _k = 0, _ref1 = shots.length; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; j = 0 <= _ref1 ? ++_k : --_k) {
        if (collided(circles[i], shots[j])) {
          delete_circ.push(i);
          delete_shot.push(j);
        }
      }
    }
    _ref2 = delete_circ.sort().reverse();
    for (_l = 0, _len = _ref2.length; _l < _len; _l++) {
      v = _ref2[_l];
      circles.splice(v, 1);
    }
    _ref3 = delete_shot.sort().reverse();
    _results = [];
    for (_m = 0, _len1 = _ref3.length; _m < _len1; _m++) {
      v = _ref3[_m];
      _results.push(shots.splice(v, 1));
    }
    return _results;
  };
  collide = function(i, j) {
    var ball1, ball2, dx, dy, phi, velox_1, velox_2, veloy_1, veloy_2;
    ball1 = circles[i];
    ball2 = circles[j];
    if (ball1.color_index + ball2.color_index > 0) {
      ball1.color_index = 1;
      ball2.color_index = 1;
    }
    dx = ball1.x - ball2.x;
    dy = ball1.y - ball2.y;
    phi = Math.atan2(dy, dx);
    velox_1 = ball2.speed * Math.cos(ball2.angle - phi) * Math.cos(phi) + ball1.speed * Math.sin(ball1.angle - phi) * Math.cos(phi + Math.PI / 2);
    veloy_1 = ball2.speed * Math.cos(ball2.angle - phi) * Math.sin(phi) + ball1.speed * Math.sin(ball1.angle - phi) * Math.sin(phi + Math.PI / 2);
    velox_2 = ball1.speed * Math.cos(ball1.angle - phi) * Math.cos(phi) + ball2.speed * Math.sin(ball2.angle - phi) * Math.cos(phi + Math.PI / 2);
    veloy_2 = ball1.speed * Math.cos(ball1.angle - phi) * Math.sin(phi) + ball2.speed * Math.sin(ball2.angle - phi) * Math.sin(phi + Math.PI / 2);
    ball1.angle = Math.atan2(veloy_1, velox_1);
    ball2.angle = Math.atan2(veloy_2, velox_2);
    ball1.speed = Math.sqrt(Math.pow(velox_1, 2) + Math.pow(veloy_1, 2));
    ball2.speed = Math.sqrt(Math.pow(velox_2, 2) + Math.pow(veloy_2, 2));
    circles[i] = updateCircle(ball1);
    return circles[j] = updateCircle(ball2);
  };
  drawCircle = function(circ) {
    context.fillStyle = colors[circ.color_index];
    context.lineWidth = 2;
    context.beginPath();
    context.arc(circ.x, circ.y, circ.r, 0, 2 * Math.PI, false);
    context.closePath();
    context.fill();
    circ = hitWall(circ);
    circ.x += circ.velo_x;
    circ.y += circ.velo_y;
    return circ;
  };
  drawShot = function(circ) {
    context.fillStyle = colors[circ.color_index];
    context.lineWidth = 2;
    context.beginPath();
    context.arc(circ.x, circ.y, circ.r, 0, 2 * Math.PI, false);
    context.closePath();
    context.fill();
    circ.x += circ.velo_x;
    circ.y += circ.velo_y;
    return circ;
  };
  drawScreen = function() {
    var circ, num_left, _j, _k, _l, _len, _m, _ref, _ref1, _ref2, _results;
    context.fillStyle = "#111";
    context.strokeStyle = "#111";
    context.lineWidth = 4;
    context.fillRect(0, 0, w, h);
    context.strokeRect(0, 0, w, h);
    for (_j = 0, _len = circles.length; _j < _len; _j++) {
      circ = circles[_j];
      if (circ.color_index === 0 && Math.random() < pr_shot) {
        shots.push(createShot(circ.x, circ.y));
      }
    }
    for (i = _k = 0, _ref = shots.length; 0 <= _ref ? _k < _ref : _k > _ref; i = 0 <= _ref ? ++_k : --_k) {
      shots[i] = drawShot(shots[i]);
    }
    check4deaths();
    cleanShots();
    check4collisions();
    for (i = _l = 0, _ref1 = circles.length; 0 <= _ref1 ? _l < _ref1 : _l > _ref1; i = 0 <= _ref1 ? ++_l : --_l) {
      circles[i] = drawCircle(circles[i]);
    }
    num_left = num_white();
    if (num_left === 1) {
      _results = [];
      for (i = _m = 0, _ref2 = circles.length; 0 <= _ref2 ? _m < _ref2 : _m > _ref2; i = 0 <= _ref2 ? ++_m : --_m) {
        _results.push(circles[i].color_index = 1 - circles[i].color_index);
      }
      return _results;
    }
  };
  stop = false;
  gameLoop = function() {
    document.onkeydown = function(e) {
      var keypress;
      keypress = String.fromCharCode(e.keyCode).toLowerCase();
      if (keypress === "r") {
        console.log("reverse");
        return circles = circles.map(function(circ) {
          circ.angle = circ.angle + Math.PI;
          return updateCircle(circ);
        });
      } else if (stop) {
        console.log("start");
        stop = false;
        return gameLoop();
      } else {
        console.log("stop");
        return stop = true;
      }
    };
    if (!stop) {
      window.setTimeout(gameLoop, delay);
    }
    return drawScreen();
  };
  return gameLoop();
};

window.onload = canvasApp;
