// Generated by CoffeeScript 1.12.5
var data, h, n, points, radius, simulation, svg, tick_action, w;

n = 100;

radius = 5;

h = 500;

w = 500;

svg = d3.select("body").insert("svg").attr("height", h).attr("width", w);

svg.insert("rect").attr("height", h).attr("width", w).attr("x", 0).attr("y", 0).attr("fill", "#ddd");

data = d3.range(n).map(function(i) {
  return {
    x: Math.random() * w,
    y: Math.random() * h
  };
});

data = data.map(function(d) {
  return {
    x: d.x,
    y: d.y,
    true_x: d.x,
    true_y: d.y
  };
});

svg.append("line").attr("x1", w / 2).attr("x2", w / 2).attr("y1", 0).attr("y2", h).attr("stroke", "white").attr("stroke-width", 3);

points = svg.selectAll("empty").data(data).enter().insert("circle").attr("cx", function(d) {
  return d.x;
}).attr("cy", function(d) {
  return d.y;
}).attr("r", radius).attr("fill", "slateblue");

d3.range(n).map(function(i) {
  return data[i].fy = data[i].y;
});

tick_action = function() {
  return points.attr("cx", function(d) {
    return d.x;
  }).attr("cy", function(d) {
    return d.y;
  });
};

simulation = d3.forceSimulation(data).force("x", d3.forceX(w / 2)).force("collide", d3.forceCollide(radius * 1.1)).on("tick", tick_action);
