// Generated by CoffeeScript 1.6.2
(function() {
  var draw;

  draw = function(data) {
    var altpink, darkBlue, darkGray, darkRed, drawCurves, h, h2, i, ih, iw, j, k, kmaxhere, kmaxloc, lab, labelcolor, lightGray, llList, mCurve, maincolor, maxLL, minLL, nm, nmaxhere, nmaxloc, nodig, np, onedig, pCurve, pad, panels, pink, purple, svg, ticks, titlecolor, totalh, totalw, twodig, w, xScaleImg, xScalemp, yScaleImg, yScalemp, zScaleImg, _i, _j, _k, _l, _m, _n, _o, _p, _ref, _ref1, _ref2, _results;

    d3.select("p#loading").remove();
    d3.select("div#legend").style("opacity", 1);
    darkBlue = "darkslateblue";
    lightGray = d3.rgb(230, 230, 230);
    darkGray = d3.rgb(200, 200, 200);
    pink = "hotpink";
    altpink = "#E9CFEC";
    purple = "#8C4374";
    darkRed = "crimson";
    labelcolor = "black";
    titlecolor = "blue";
    maincolor = "blue";
    nodig = d3.format(".0f");
    onedig = d3.format(".1f");
    twodig = d3.format(".2f");
    minLL = [];
    maxLL = [];
    nmaxloc = [];
    kmaxloc = [];
    for (i = _i = 0, _ref = data.nll.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      minLL[i] = data.nll[i][0][0];
      maxLL[i] = data.nll[i][0][0];
      nmaxhere = data.nll[i][0][0];
      kmaxhere = data.kll[i][0][0];
      nmaxloc[i] = {
        row: 0,
        col: 0
      };
      kmaxloc[i] = {
        row: 0,
        col: 0
      };
      for (j in data.nll[i]) {
        for (k in data.nll[i][j]) {
          if (minLL[i] > data.nll[i][j][k]) {
            minLL[i] = data.nll[i][j][k];
          }
          if (maxLL[i] < data.nll[i][j][k]) {
            maxLL[i] = data.nll[i][j][k];
          }
          if (nmaxhere < data.nll[i][j][k]) {
            nmaxhere = data.nll[i][j][k];
            nmaxloc[i] = {
              row: k,
              col: j
            };
          }
          if (minLL[i] > data.kll[i][j][k]) {
            minLL[i] = data.kll[i][j][k];
          }
          if (maxLL[i] < data.kll[i][j][k]) {
            maxLL[i] = data.kll[i][j][k];
          }
          if (kmaxhere < data.kll[i][j][k]) {
            kmaxhere = data.kll[i][j][k];
            kmaxloc[i] = {
              row: k,
              col: j
            };
          }
        }
      }
    }
    llList = [];
    for (i = _j = 0, _ref1 = data.nll.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
      llList[i] = [];
      for (j in data.nll[i]) {
        for (k in data.nll[i][j]) {
          llList[i].push({
            col: j,
            row: k,
            nll: data.nll[i][j][k],
            kll: data.kll[i][j][k],
            chr: i
          });
        }
      }
    }
    w = 300;
    pad = {
      left: 60,
      top: 40,
      right: 25,
      bottom: 35,
      inner: 0
    };
    h = w;
    h2 = (h - pad.top - pad.bottom) / 2;
    totalh = w + pad.top + pad.bottom;
    totalw = 3 * (w + pad.left + pad.right);
    console.log("totalw = " + totalw + "; totalh = " + totalh);
    iw = [w, w, w, w];
    ih = [h, h, h2, h2];
    svg = [];
    panels = [];
    xScaleImg = [];
    yScaleImg = [];
    zScaleImg = [];
    xScalemp = [];
    yScalemp = [];
    _results = [];
    for (i = _k = 0, _ref2 = data.nll.length; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; i = 0 <= _ref2 ? ++_k : --_k) {
      d3.select("div#heatmap_fig").append("hr").style("border", 0).style("width", "100%").style("color", "black").style("background-color", "black").style("height", "2px");
      d3.select("div#heatmap_fig").append("h3").text("Chromosome " + (i + 1));
      svg[i] = d3.select("div#heatmap_fig").append("svg").attr("height", totalh).attr("width", totalw);
      panels[i] = [];
      panels[i][0] = svg[i].append("g").attr("id", "n_image_" + i).attr("transform", "translate(" + pad.left + "," + pad.top + ")");
      panels[i][1] = svg[i].append("g").attr("id", "k_image_" + i).attr("transform", "translate(" + (pad.left * 2 + pad.right + w) + "," + pad.top + ")");
      panels[i][2] = svg[i].append("g").attr("id", "p_line_" + i).attr("transform", "translate(" + (pad.left * 3 + pad.right * 2 + w * 2) + "," + pad.top + ")");
      panels[i][3] = svg[i].append("g").attr("id", "m_line_" + i).attr("transform", "translate(" + (pad.left * 3 + pad.right * 2 + w * 2) + "," + (pad.top * 2 + pad.bottom + h2) + ")");
      for (j = _l = 0; _l < 4; j = ++_l) {
        panels[i][j].append("rect").attr("height", ih[j]).attr("width", iw[j]).attr("fill", "white").attr("stroke", "black").attr("stroke-width", 1);
      }
      nm = data.nll[i].length;
      np = data.nll[i][0].length;
      xScaleImg[i] = d3.scale.ordinal().domain(data.m.slice(0, nm)).rangeBands([0, w]);
      yScaleImg[i] = d3.scale.ordinal().domain(data.p.slice(0, np)).rangeBands([h, 0]);
      zScaleImg[i] = d3.scale.linear().domain([-20, maxLL[i]]).range([darkBlue, "white"]).clamp(true);
      for (j = _m = 0; _m <= 1; j = ++_m) {
        panels[i][j].append("text").attr("id", "loglik" + i + j).text("").attr("x", w / 2).attr("y", -pad.top * 0.25).attr("text-anchor", "middle").attr("dominant-baseline", "middle").attr("fill", labelcolor);
        panels[i][j].append("text").text(["Nicola", "Karl"][j]).attr("x", w / 2).attr("y", -pad.top * 0.75).attr("text-anchor", "middle").attr("dominant-baseline", "middle").attr("fill", [darkRed, darkBlue][j]);
      }
      for (j = _n = 2; _n <= 3; j = ++_n) {
        panels[i][j].append("text").attr("id", "mptitle" + i + j).text("").attr("x", w / 2).attr("y", -pad.top * 0.3).attr("text-anchor", "middle").attr("dominant-baseline", "middle").attr("fill", labelcolor);
      }
      xScalemp[i] = [];
      xScalemp[i][0] = d3.scale.linear().domain([0, data.p[np - 1]]).range([pad.inner, w - pad.inner]);
      xScalemp[i][1] = d3.scale.linear().domain([0, data.m[nm - 1]]).range([pad.inner, w - pad.inner]);
      yScalemp[i] = d3.scale.linear().domain([minLL[i], maxLL[i]]).range([h2 - pad.inner, pad.inner]);
      pCurve = function(mindex, chr, dat) {
        return d3.svg.line().x(function(d) {
          return xScalemp[chr][0](d);
        }).y(function(d, i) {
          return yScalemp[chr](dat[chr][mindex][i]);
        });
      };
      mCurve = function(pindex, chr, dat) {
        return d3.svg.line().x(function(d) {
          return xScalemp[chr][1](d);
        }).y(function(d, i) {
          return yScalemp[chr](dat[chr][i][pindex]);
        });
      };
      drawCurves = function(mindex, pindex, chr) {
        var mcurves, pcurves;

        pcurves = panels[chr][2].append("g").attr("class", "mpcurve");
        pcurves.append("path").datum(data.p).attr("d", pCurve(mindex, chr, data.nll)).attr("stroke", darkRed).attr("fill", "none").attr("stroke-width", "2");
        pcurves.append("path").datum(data.p).attr("d", pCurve(mindex, chr, data.kll)).attr("stroke", darkBlue).attr("fill", "none").attr("stroke-width", "2");
        mcurves = panels[chr][3].append("g").attr("class", "mpcurve");
        mcurves.append("path").datum(data.m.slice(0, data.nll[chr].length)).attr("d", mCurve(pindex, chr, data.nll)).attr("stroke", darkRed).attr("fill", "none").attr("stroke-width", "2");
        return mcurves.append("path").datum(data.m.slice(0, data.nll[chr].length)).attr("d", mCurve(pindex, chr, data.kll)).attr("stroke", darkBlue).attr("fill", "none").attr("stroke-width", "2");
      };
      panels[i][0].append("g").attr("id", "n_imgrect_" + i).selectAll("empty").data(llList[i]).enter().append("rect").attr("x", function(d) {
        return xScaleImg[i](data.m[d.col]);
      }).attr("y", function(d) {
        return yScaleImg[i](data.p[d.row]);
      }).attr("width", xScaleImg[i].rangeBand()).attr("height", yScaleImg[i].rangeBand()).attr("fill", function(d) {
        return zScaleImg[i](d.nll);
      }).on("mouseover", function(d) {
        var title0, title1;

        title0 = "loglik = " + (onedig(d.nll));
        title1 = "loglik = " + (onedig(d.kll));
        d3.select("text#loglik" + d.chr + "0").text(title0);
        d3.select("text#loglik" + d.chr + "1").text(title1);
        d3.select("text#mptitle" + d.chr + "2").text("m = " + data.m[d.col]);
        d3.select("text#mptitle" + d.chr + "3").text("p = " + data.p[d.row]);
        panels[d.chr][0].append("rect").attr("id", "mouseover0").attr("x", xScaleImg[d.chr](data.m[d.col])).attr("y", yScaleImg[d.chr](data.p[d.row])).attr("width", xScaleImg[d.chr].rangeBand()).attr("height", yScaleImg[d.chr].rangeBand()).style("pointer-events", "none").attr("fill", "none").attr("stroke", "green").attr("stroke-width", 2);
        panels[d.chr][1].append("rect").attr("id", "mouseover1").attr("x", xScaleImg[d.chr](data.m[d.col])).attr("y", yScaleImg[d.chr](data.p[d.row])).attr("width", xScaleImg[d.chr].rangeBand()).attr("height", yScaleImg[d.chr].rangeBand()).style("pointer-events", "none").attr("fill", "none").attr("stroke", "green").attr("stroke-width", 2);
        return drawCurves(d.col, d.row, d.chr);
      }).on("mouseout", function(d) {
        d3.select("text#loglik" + d.chr + "0").text("");
        d3.select("text#loglik" + d.chr + "1").text("");
        d3.select("text#mptitle" + d.chr + "2").text("");
        d3.select("text#mptitle" + d.chr + "3").text("");
        d3.select("rect#mouseover0").remove();
        d3.select("rect#mouseover1").remove();
        return d3.selectAll("g.mpcurve").remove();
      });
      panels[i][1].append("g").attr("id", "n_imgrect_" + i).selectAll("empty").data(llList[i]).enter().append("rect").attr("x", function(d) {
        return xScaleImg[i](data.m[d.col]);
      }).attr("y", function(d) {
        return yScaleImg[i](data.p[d.row]);
      }).attr("width", xScaleImg[i].rangeBand()).attr("height", yScaleImg[i].rangeBand()).attr("fill", function(d) {
        return zScaleImg[i](d.kll);
      }).on("mouseover", function(d) {
        var title0, title1;

        title0 = "loglik = " + (onedig(d.nll));
        title1 = "loglik = " + (onedig(d.kll));
        d3.select("text#loglik" + d.chr + "0").text(title0);
        d3.select("text#loglik" + d.chr + "1").text(title1);
        d3.select("text#mptitle" + d.chr + "2").text("m = " + data.m[d.col]);
        d3.select("text#mptitle" + d.chr + "3").text("p = " + data.p[d.row]);
        panels[d.chr][0].append("rect").attr("id", "mouseover0").attr("x", xScaleImg[d.chr](data.m[d.col])).attr("y", yScaleImg[d.chr](data.p[d.row])).attr("width", xScaleImg[d.chr].rangeBand()).attr("height", yScaleImg[d.chr].rangeBand()).style("pointer-events", "none").attr("fill", "none").attr("stroke", "green").attr("stroke-width", 2);
        panels[d.chr][1].append("rect").attr("id", "mouseover1").attr("x", xScaleImg[d.chr](data.m[d.col])).attr("y", yScaleImg[d.chr](data.p[d.row])).attr("width", xScaleImg[d.chr].rangeBand()).attr("height", yScaleImg[d.chr].rangeBand()).style("pointer-events", "none").attr("fill", "none").attr("stroke", "green").attr("stroke-width", 2);
        return drawCurves(d.col, d.row, d.chr);
      }).on("mouseout", function(d) {
        d3.select("text#loglik" + d.chr + "0").text("");
        d3.select("text#loglik" + d.chr + "1").text("");
        d3.select("text#mptitle" + d.chr + "2").text("");
        d3.select("text#mptitle" + d.chr + "3").text("");
        d3.select("rect#mouseover0").remove();
        d3.select("rect#mouseover1").remove();
        return d3.selectAll("g.mpcurve").remove();
      });
      panels[i][0].append("rect").attr("x", xScaleImg[i](data.m[nmaxloc[i].col])).attr("y", yScaleImg[i](data.p[nmaxloc[i].row])).attr("width", xScaleImg[i].rangeBand()).attr("height", yScaleImg[i].rangeBand()).attr("fill", "none").attr("stroke", darkRed).attr("stroke-width", 2);
      panels[i][1].append("rect").attr("x", xScaleImg[i](data.m[kmaxloc[i].col])).attr("y", yScaleImg[i](data.p[kmaxloc[i].row])).attr("width", xScaleImg[i].rangeBand()).attr("height", yScaleImg[i].rangeBand()).attr("fill", "none").attr("stroke", darkRed).attr("stroke-width", 2);
      lab = [];
      for (j = _o = 0; _o <= 1; j = ++_o) {
        lab[j] = panels[i][j].append("g");
        lab[j].append("text").text("m").attr("x", w / 2).attr("y", h + pad.bottom * 0.7).attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle");
        lab[j].append("text").text("p").attr("x", -pad.left * 0.7).attr("y", h / 2).attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle");
        lab[j].selectAll("empty").data([0, 5, 10]).enter().append("text").text(function(d) {
          return d;
        }).attr("x", function(d) {
          return xScaleImg[i](d) + xScaleImg[i].rangeBand() / 2;
        }).attr("y", h + pad.bottom * 0.3).attr("fill", labelcolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle");
        lab[j].selectAll("empty").data([0, 0.03, 0.06, 0.09]).enter().append("text").text(function(d) {
          return twodig(d);
        }).attr("x", -pad.left * 0.05).attr("y", function(d) {
          return yScaleImg[i](d) + yScaleImg[i].rangeBand() / 2;
        }).attr("fill", labelcolor).attr("text-anchor", "end").attr("dominant-baseline", "middle");
      }
      ticks = [[0, 0.03, 0.06, 0.09], [0, 3, 6, 9, 12]];
      for (j = _p = 2; _p <= 3; j = ++_p) {
        lab[j] = panels[i][j].append("g");
        lab[j].append("text").text(["p", "m"][j - 2]).attr("x", w / 2).attr("y", h2 + pad.bottom * 0.7).attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle");
        lab[j].append("text").text("loglik").attr("x", -pad.left * 0.7).attr("y", h2 / 2).attr("fill", titlecolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle").attr("transform", "rotate(270, " + (-pad.left * 0.7) + ", " + (h2 / 2) + ")");
        lab[j].selectAll("empty").data(ticks[j - 2]).enter().append("text").text(function(d) {
          if (j === 2) {
            return twodig(d);
          }
          return nodig(d);
        }).attr("x", function(d) {
          return xScalemp[i][j - 2](d);
        }).attr("y", h2 + pad.bottom * 0.3).attr("fill", labelcolor).attr("text-anchor", "middle").attr("dominant-baseline", "middle");
        lab[j].selectAll("empty").data(ticks[j - 2]).enter().append("line").attr("x1", function(d) {
          return xScalemp[i][j - 2](d);
        }).attr("x2", function(d) {
          return xScalemp[i][j - 2](d);
        }).attr("y1", 0).attr("y2", h2).attr("stroke", lightGray).attr("stroke-width", "2");
        lab[j].selectAll("empty").data(yScalemp[i].ticks(3)).enter().append("text").text(function(d) {
          return d;
        }).attr("x", -pad.left * 0.05).attr("y", function(d) {
          return yScalemp[i](d);
        }).attr("fill", labelcolor).attr("text-anchor", "end").attr("dominant-baseline", "middle");
        lab[j].selectAll("empty").data(yScalemp[i].ticks(3)).enter().append("line").attr("x1", 0).attr("x2", w).attr("y1", function(d) {
          return yScalemp[i](d);
        }).attr("y2", function(d) {
          return yScalemp[i](d);
        }).attr("stroke", lightGray).attr("stroke-width", "2");
      }
      _results.push((function() {
        var _q, _results1;

        _results1 = [];
        for (j = _q = 0; _q < 4; j = ++_q) {
          _results1.push(panels[i][j].append("rect").attr("height", ih[j]).attr("width", iw[j]).attr("fill", "none").attr("stroke", "black").attr("stroke-width", 1));
        }
        return _results1;
      })());
    }
    return _results;
  };

  d3.json("loglik.json", draw);

}).call(this);
