lod_random.js: lod_random.coffee
	coffee -bc lod_random.coffee

web: lod_random.js
	scp index.html lod_random.coffee lod_random.css lod_random.js data_random.json d3-tip.css broman-2.biostat.wisc.edu:public_html/D3/lod_random/
