// Generated by CoffeeScript 1.8.0
var h, halfh, margin, totalh, totalw, w;

h = 300;

w = 600;

margin = {
  left: 60,
  top: 40,
  right: 40,
  bottom: 40,
  inner: 5
};

halfh = h + margin.top + margin.bottom;

totalh = halfh * 2;

totalw = w + margin.left + margin.right;

d3.json("data.json", function(data) {
  var chrrect, mychart;
  mychart = lodchart().lodvarname("lod.em").height(h).width(w).margin(margin);
  d3.select("div#topchart").datum(data).call(mychart);
  chrrect = mychart.chrSelect();
  chrrect.on("mouseover", function() {
    return d3.select(this).attr("fill", "#E9CFEC");
  }).on("mouseout", function(d, i) {
    return d3.select(this).attr("fill", function() {
      if (i % 2) {
        return "#c8c8c8";
      }
      return "#e6e6e6";
    });
  });
  return mychart.markerSelect().on("click", function(d) {
    var r;
    r = d3.select(this).attr("r");
    return d3.select(this).transition().duration(500).attr("r", r * 3).transition().duration(500).attr("r", r);
  });
});

d3.json("data.json", function(data) {
  var chart1, chart2, mychart_em, mychart_hk, svg;
  mychart_em = lodchart().lodvarname("lod.em").height(h).width(w).margin(margin).ylab("LOD score (by EM)").pointsize(1).nyticks(9).title("Standard interval mapping");
  mychart_hk = lodchart().lodvarname("lod.hk").height(h).width(w).margin(margin).ylab("LOD score (by H-K)").linecolor("Crimson").yticks([0, 1, 2, 4, 6, 8]).title("Haley-Knott regression");
  svg = d3.select("div#bottomchart").append("svg").attr("height", totalh).attr("width", totalw);
  chart1 = svg.append("g").attr("id", "chart1");
  chart2 = svg.append("g").attr("id", "chart2").attr("transform", "translate(0, " + halfh + ")");
  chart1.datum(data).call(mychart_em);
  return chart2.datum(data).call(mychart_hk);
});
