// Generated by CoffeeScript 1.8.0
var h, w;

h = 600;

w = 600;

d3.json("data.json", function(data) {
  var mychart;
  mychart = heatmap().height(h).width(w).zthresh(0.5);
  return d3.select("div#chart").datum(data).call(mychart);
});
